# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NIH-CFDE FAIR COOKBOOK
author: ''
logo: content/images/logo/CFDE-logo-contrast.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - html_image

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://nih-cfde.github.io/the-fair-cookbook/  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  baseurl: https://nih-cfde.github.io/the-fair-cookbook/
  extra_navbar: ''
  #google_analytics_id: ''
  favicon: content/images/logo/CFDE-logo.ico
  extra_footer: |
    This project is supported by NIH CFDE program <img src="/the-fair-cookbook/images/logo/CFDE-logo.png" alt="NIH flag" height="20" />

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['assets']
