name: Deploy to gh-pages
on:
  push:
    branches:
      - new
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Preparing pip
      run: |
        python -m pip install --upgrade pip
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
    - name: Building site
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        bundle install --path vendor/bundle
        make install
        make site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
