name: Deploy to gh-pages
on:
  push:
    branches:
      - new
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
    - name: Install ruby dependencies
      run: |
        gem install bundler:1.17.2
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: Building site
      run: |
        make install
        make site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
